// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearMsgs():Promise<void>;

export function GetFilePath():Promise<string>;

export function GetIsRunning():Promise<boolean>;

export function GetMsgs():Promise<Array<string>>;

export function GetSyringeProcessInfo():Promise<main.ProcessInfo>;

export function GetTestProcessInfo():Promise<main.ProcessInfo>;

export function KillTest():Promise<boolean>;

export function OpenEXEDialog():Promise<boolean>;

export function RunTest(arg1:string):Promise<boolean>;

export function StartUDP():Promise<void>;
