// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFilePath() {
  return window['go']['main']['App']['GetFilePath']();
}

export function GetIsRunning() {
  return window['go']['main']['App']['GetIsRunning']();
}

export function KillTest() {
  return window['go']['main']['App']['KillTest']();
}

export function OpenEXEDialog() {
  return window['go']['main']['App']['OpenEXEDialog']();
}

export function RunTest() {
  return window['go']['main']['App']['RunTest']();
}

export function StartUDP() {
  return window['go']['main']['App']['StartUDP']();
}
