// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFilePath():Promise<string>;

export function GetIsRunning():Promise<boolean>;

export function KillTest():Promise<boolean>;

export function OpenEXEDialog():Promise<boolean>;

export function RunTest():Promise<boolean>;

export function StartUDP():void;
