// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearMsgs() {
  return window['go']['main']['App']['ClearMsgs']();
}

export function GetFilePath() {
  return window['go']['main']['App']['GetFilePath']();
}

export function GetIsRunning() {
  return window['go']['main']['App']['GetIsRunning']();
}

export function GetMsgs() {
  return window['go']['main']['App']['GetMsgs']();
}

export function GetStatistics() {
  return window['go']['main']['App']['GetStatistics']();
}

export function GetSyringeProcessInfo() {
  return window['go']['main']['App']['GetSyringeProcessInfo']();
}

export function GetTestProcessInfo() {
  return window['go']['main']['App']['GetTestProcessInfo']();
}

export function KillTest() {
  return window['go']['main']['App']['KillTest']();
}

export function OpenEXEDialog() {
  return window['go']['main']['App']['OpenEXEDialog']();
}

export function RunTest(arg1) {
  return window['go']['main']['App']['RunTest'](arg1);
}

export function StartUDP() {
  return window['go']['main']['App']['StartUDP']();
}
